import express from "express";
import http from "http";
import { Server } from "socket.io";
import { exec } from "child_process";
import path from "path";
import fs from "fs";
import { fileURLToPath } from "url";
import { attachMatchmaking } from "./services/matchmaking.js";
import { 
  getAllQuestions, 
  addQuestion, 
  deleteQuestion, 
  forceSeedQuestions,
  deleteAllAutoGeneratedQuestions,
  getAllUsers,
  deleteUser,
  getAllMatches,
  updateUserEloById
} from "./db/database.js";

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const app = express();
const server = http.createServer(app);

app.use(express.json());
app.use((req, res, next) => {
  res.header("Access-Control-Allow-Origin", "*");
  res.header("Access-Control-Allow-Headers", "Content-Type");
  res.header("Access-Control-Allow-Methods", "GET, POST, DELETE, OPTIONS");
  next();
});

const io = new Server(server, {
  cors: { origin: "*" },
});

app.get("/", (_req, res) => {
  res.json({ ok: true, name: "qna-1v1-server" });
});

// Admin Routes
app.get("/admin/questions", async (req, res) => {
  try {
    const questions = await getAllQuestions();
    res.json(questions);
  } catch (err) {
    res.status(500).json({ error: err.message });
  }
});

app.post("/admin/questions", async (req, res) => {
  try {
    const q = req.body;
    // Basic validation
    if (!q.question) return res.status(400).json({ error: "Question requise" });
    
    const result = await addQuestion(q);
    res.json(result);
  } catch (err) {
    res.status(500).json({ error: err.message });
  }
});

app.post("/admin/questions/import", async (req, res) => {
  try {
    console.log("Importing default questions via Admin API...");
    await forceSeedQuestions();
    const questions = await getAllQuestions();
    res.json(questions);
  } catch (err) {
    console.error("Error importing:", err);
    res.status(500).json({ error: err.message });
  }
});

app.post("/admin/sync-liquipedia", (req, res) => {
  console.log("[Admin] Starting Liquipedia Import process...");
  
  // 1. Generate Questions
  const generateScript = path.resolve(__dirname, "../scripts/generate-questions.js");
  const importScript = path.resolve(__dirname, "../scripts/import-questions.js");

  // We use exec to run the scripts.
  
  // Create cache directory if it doesn't exist
  const cacheDir = path.resolve(__dirname, "../cache");
  if (!fs.existsSync(cacheDir)) {
      fs.mkdirSync(cacheDir, { recursive: true });
  }

  exec(`node "${generateScript}"`, { cwd: path.dirname(generateScript) }, async (error, stdout, stderr) => {
      if (error) {
          console.error(`exec error: ${error}`);
          return res.status(500).json({ error: "Generation failed", details: stderr + "\n" + stdout });
      }
      console.log(`[Generation] ${stdout}`);

      try {
          // 1.5 Clear old questions before importing new ones to avoid stale HLTV data
          console.log("[Admin] Clearing old questions...");
          await deleteAllAutoGeneratedQuestions();

          // 2. Import Questions
          exec(`node "${importScript}"`, { cwd: path.dirname(importScript) }, async (error2, stdout2, stderr2) => {
              if (error2) {
                  console.error(`exec error: ${error2}`);
                  return res.status(500).json({ error: "Import failed", details: stderr2 + "\n" + stdout2 });
              }
              console.log(`[Import] ${stdout2}`);
              
              // 3. Update question list and return
              try {
                const questions = await getAllQuestions();
                res.json({ success: true, count: questions.length, log: stdout2 });
              } catch(e) {
                res.status(500).json({ error: e.message });
              }
          });
      } catch (dbErr) {
          console.error("DB Clear error:", dbErr);
          res.status(500).json({ error: "Database cleanup failed" });
      }
  });
});

app.delete("/admin/questions/:id", async (req, res) => {
  try {
    const { id } = req.params;
    await deleteQuestion(id);
    res.json({ success: true, id });
  } catch (err) {
    res.status(500).json({ error: err.message });
  }
});

// Admin Users Routes
app.get("/admin/users", async (req, res) => {
    try {
        const users = await getAllUsers();
        res.json(users);
    } catch (err) {
        res.status(500).json({ error: err.message });
    }
});

app.delete("/admin/users/:id", async (req, res) => {
    try {
        await deleteUser(req.params.id);
        res.json({ success: true });
    } catch (err) {
        res.status(500).json({ error: err.message });
    }
});

app.post("/admin/users/:id/elo", async (req, res) => {
    try {
        const { elo } = req.body;
        await updateUserEloById(req.params.id, elo);
        res.json({ success: true, elo });
    } catch (err) {
        res.status(500).json({ error: err.message });
    }
});

// Admin Match History
app.get("/admin/matches", async (req, res) => {
    try {
        const matches = await getAllMatches();
        res.json(matches);
    } catch (err) {
        res.status(500).json({ error: err.message });
    }
});

attachMatchmaking(io);

const PORT = process.env.PORT || 3001;
server.listen(PORT, () => {
  console.log(`Server running on http://localhost:${PORT}`);
});
